.gitignore, app/models/user.rb, config/routes.rb
=> removed confirmable from user

README.md
Add codeship ci for automated build & test.
https://codeship.com/
=> Add codeship ci

.dockerignore, Dockerfile, config/database.yml, db/schema.rb, docker-compose.yml
update dockerignore to ignore tmp folder
update dockerfile and database.yml to setup test env
=> Added docker-compose

config/initializers/doorkeeper.rb, config/secrets.yml, db/schema.rb, docker-compose.yml
Update docker-compose.yml to take in env var
Update secrets.yml to take in env var
=> Docker compose

docker-compose.yml
- Short description of overall goals of the pull request's commits
- Links to libraries you added
=> Remove command from docker-compose.yml

README.md
- Short description of overall goals of the pull request's commits
- Links to libraries you added
=> Update readme for testing

README.md
Update Readme on how to run using docker-compose
=> Update Readme on how to run using docker-compose

app/admin/agencies.rb, app/admin/comments.rb, app/admin/companies.rb, app/admin/doorkeeper_access_tokens.rb, app/admin/likes.rb, app/admin/products.rb, app/admin/reviews.rb, app/admin/services.rb, app/controllers/tokens_controller.rb, config/initializers/active_admin.rb, config/routes.rb, spec/controllers/tokens_controller_spec.rb, spec/requests/agencies_spec.rb, spec/requests/comments_spec.rb, spec/requests/companies_spec.rb, spec/requests/likes_spec.rb, spec/requests/products_spec.rb, spec/requests/reviews_spec.rb, spec/requests/services_spec.rb, spec/requests/statistics_spec.rb, spec/requests/tokens_spec.rb, spec/routing/tokens_routing_spec.rb, spec/support/api_login_helper.rb
- Allow app to request for a new token through oauth/refresh by setting the authorization header and passing their name and password in the body
=> Add refresh token

db/seeds.rb
- Allow admin user to be seeded on test  and dev
=> allow admin user to be seeded on test also

Gemfile, Gemfile.lock, app/serializers/company_serializer.rb, spec/controllers/companies_controller_spec.rb, spec/models/company_spec.rb, spec/requests/companies_spec.rb, spec/serializers/company_serializer_spec.rb
- Developer can get companies from Companies endpoint
- 154788840
- Active Model Serializer https://github.com/rails-api/active_model_serializers
=> Add company index

Gemfile, Gemfile.lock, app/controllers/companies_controller.rb, app/controllers/concerns/render_errors.rb, app/serializers/company_serializer.rb, spec/controllers/companies_controller_spec.rb, spec/models/company_spec.rb, spec/requests/companies_spec.rb, spec/serializers/company_serializer_spec.rb, spec/spec_helper.rb
- Developer can get a specified company from Companies endpoint
- Some refactored function that affects #38 specs
- 154788839
*please merge #38 first
=> Add company show

app/admin/admin_users.rb, app/admin/apps.rb
- Added missing "description" field to app in admin console, allowed passwords to remain unchange on editing form for app and admin_user
- 154654426
=> fixed ActiveAdmin Console

Gemfile, Gemfile.lock, app/admin/admin_users.rb, app/admin/apps.rb, app/controllers/companies_controller.rb, app/controllers/concerns/render_errors.rb, app/serializers/company_serializer.rb, spec/controllers/agencies_controller_spec.rb, spec/controllers/comments_controller_spec.rb, spec/controllers/companies_controller_spec.rb, spec/controllers/likes_controller_spec.rb, spec/controllers/products_controller_spec.rb, spec/controllers/reviews_controller_spec.rb, spec/controllers/services_controller_spec.rb, spec/controllers/statistics_controller_spec.rb, spec/controllers/tokens_controller_spec.rb, spec/models/company_spec.rb, spec/requests/agencies_spec.rb, spec/requests/comments_spec.rb, spec/requests/companies_spec.rb, spec/requests/likes_spec.rb, spec/requests/products_spec.rb, spec/requests/reviews_spec.rb, spec/requests/services_spec.rb, spec/requests/statistics_spec.rb, spec/requests/tokens_spec.rb, spec/serializers/company_serializer_spec.rb, spec/spec_helper.rb
- Developer can create a new company from Companies endpoint
- 154788838
*please merge #39 first
=> Add company create

app/controllers/companies_controller.rb, app/models/company.rb, spec/controllers/agencies_controller_spec.rb, spec/controllers/comments_controller_spec.rb, spec/controllers/companies_controller_spec.rb, spec/controllers/likes_controller_spec.rb, spec/controllers/products_controller_spec.rb, spec/controllers/reviews_controller_spec.rb, spec/controllers/services_controller_spec.rb, spec/controllers/statistics_controller_spec.rb, spec/controllers/tokens_controller_spec.rb, spec/factories.rb, spec/models/company_spec.rb, spec/requests/agencies_spec.rb, spec/requests/comments_spec.rb, spec/requests/companies_spec.rb, spec/requests/likes_spec.rb, spec/requests/products_spec.rb, spec/requests/reviews_spec.rb, spec/requests/services_spec.rb, spec/requests/statistics_spec.rb, spec/requests/tokens_spec.rb, spec/spec_helper.rb
- Developer can update a specified company from Companies endpoint 
- Validate company aggregate score range
- 154788837
=> Add company update

app/controllers/concerns/swagger_docs/agencies.rb, app/controllers/concerns/swagger_docs/comments.rb, app/controllers/concerns/swagger_docs/companies.rb, app/controllers/concerns/swagger_docs/likes.rb, app/controllers/concerns/swagger_docs/products.rb, app/controllers/concerns/swagger_docs/reviews.rb, app/controllers/concerns/swagger_docs/services.rb, app/controllers/concerns/swagger_docs/statistics.rb, app/controllers/concerns/swagger_docs/tokens.rb, public/index.html
- Updated the routes URL for the swagger docs
- #154653947
- nil
=> Updated the routes URL for SwaggerUI

app/admin/admin_users.rb, app/admin/agencies.rb, app/admin/apps.rb, app/admin/comments.rb, app/admin/companies.rb, app/admin/doorkeeper_access_tokens.rb, app/admin/likes.rb, app/admin/products.rb, app/admin/reviews.rb, app/admin/services.rb, app/models/admin_user.rb, app/models/agency.rb, app/models/app.rb, app/models/comment.rb, app/models/like.rb, app/models/review.rb, app/models/service.rb, db/migrate/20180214053000_add_discard_to_admin_user.rb, db/migrate/20180214053014_add_discard_to_agency.rb, db/migrate/20180214053032_add_discard_to_app.rb, db/migrate/20180214053042_add_discard_to_comment.rb, db/migrate/20180214053100_add_discard_to_like.rb, db/migrate/20180214053114_add_discard_to_review.rb, db/migrate/20180214053122_add_discard_to_service.rb, db/schema.rb
- Add soft delete to admin console
=> soft delete for admin console

app/admin/admin_users.rb, app/admin/doorkeeper_access_tokens.rb
- Admin can manage application via Admin Console
- 154654426 (AC3)
=> fixed admin user cant edit and token cant delete

app/admin/admin_users.rb, app/admin/doorkeeper_access_tokens.rb, app/controllers/products_controller.rb, app/serializers/product_serializer.rb, spec/controllers/products_controller_spec.rb, spec/requests/products_spec.rb, spec/routing/products_routing_spec.rb, spec/serializers/product_serializer_spec.rb
- Add index, show, create, update, delete endpoint tests for product request and routes
- Add serializer & serializer test
- Task number from pivotal tracker:
154788639
154788640
154788637
154788636
154788634
=> Fix product specs

app/controllers/companies_controller.rb, app/models/company.rb, spec/controllers/companies_controller_spec.rb, spec/models/company_spec.rb, spec/requests/companies_spec.rb
- change company delete status code
- remove aggregate score validation
- fixed update with invalid params returning 400 instead of 404
- Task number:
154788837
155318270
155317995
=> Fix company

app/controllers/tokens_controller.rb, spec/controllers/tokens_controller_spec.rb, spec/requests/tokens_spec.rb
- remove token from refresh header and add to body
- #154830282 comment 1
=> modified how refresh token works

app/views/swagger_ui/index.html.erb
- Updated code to Swagger index page to handle ssl difference
- #154653947
- nil
=> Fix ssl issue on url

app/controllers/apidocs_controller.rb, app/controllers/concerns/swagger_docs/comments.rb, app/controllers/concerns/swagger_docs/companies.rb, app/controllers/concerns/swagger_docs/likes.rb, app/controllers/concerns/swagger_docs/products.rb, app/controllers/concerns/swagger_docs/reviews.rb, app/controllers/concerns/swagger_docs/services.rb, app/controllers/concerns/swagger_docs/statistics.rb, app/controllers/concerns/swagger_docs/tokens.rb, app/controllers/concerns/swagger_docs/users.rb, app/models/concerns/swagger_docs/app.rb, app/models/concerns/swagger_docs/comment.rb, app/models/concerns/swagger_docs/company.rb, app/models/concerns/swagger_docs/like.rb, app/models/concerns/swagger_docs/product.rb, app/models/concerns/swagger_docs/review.rb, app/models/concerns/swagger_docs/service.rb, app/models/concerns/swagger_docs/user.rb
- Added description and missing response code for all the APIs
- #154653947
- nil
=> Update swagger response code and description

deployment.sh
- Add deployment script for QA environment
- Configured at TeamCity CI
=> Docker Compose Deployment Script for QA Environment

.rubocop_enabled.yml, app/controllers/companies_controller.rb, app/models/concerns/statistics/companies.rb, spec/concerns/statistics/companies_spec.rb, spec/concerns/statistics/products_and_services_spec.rb, spec/concerns/statistics/reviews_spec.rb, spec/controllers/companies_controller_spec.rb, spec/factories/companies.rb, spec/factories/reviews.rb, spec/models/comment_spec.rb, spec/models/company_spec.rb, spec/models/like_spec.rb, spec/models/product_spec.rb, spec/models/review_spec.rb, spec/models/service_spec.rb, spec/requests/companies_spec.rb
- Test for companies concern
- 155386546
=> added concerns-spec

app/controllers/services_controller.rb, app/serializers/service_serializer.rb, spec/controllers/services_controller_spec.rb, spec/models/service_spec.rb, spec/requests/products_spec.rb, spec/requests/services_spec.rb, spec/routing/services_routing_spec.rb, spec/serializers/service_serializer_spec.rb
- Modified Service endpoint function
- Added Service endpoint spec
- #154788781
- #154788780
- #154788778
- #154788777
- #154788775
- nil
=> Service endpoint

spec/controllers/comments_controller_spec.rb, spec/controllers/likes_controller_spec.rb, spec/controllers/reviews_controller_spec.rb, spec/controllers/services_controller_spec.rb, spec/controllers/statistics_controller_spec.rb, spec/controllers/tokens_controller_spec.rb, spec/models/app_spec.rb, spec/requests/comments_spec.rb, spec/requests/likes_spec.rb, spec/requests/reviews_spec.rb, spec/requests/services_spec.rb, spec/requests/statistics_spec.rb, spec/requests/tokens_spec.rb, spec/support/api_login_helper.rb
- Removed unnecessary class variable
- #155455861
- nil
=> Removed unneccessary class variable

app/controllers/apidocs_controller.rb, app/controllers/concerns/swagger_docs/comments.rb, app/controllers/concerns/swagger_docs/companies.rb, app/controllers/concerns/swagger_docs/likes.rb, app/controllers/concerns/swagger_docs/products.rb, app/controllers/concerns/swagger_docs/reviews.rb, app/controllers/concerns/swagger_docs/services.rb, app/controllers/concerns/swagger_docs/statistics.rb, app/controllers/concerns/swagger_docs/tokens.rb, app/controllers/concerns/swagger_docs/users.rb, app/models/concerns/swagger_docs/app.rb, app/models/concerns/swagger_docs/company.rb, app/models/concerns/swagger_docs/product.rb, app/models/concerns/swagger_docs/review.rb, app/models/concerns/swagger_docs/service.rb, app/views/swagger_ui/index.html.erb, config/routes.rb, spec/routing/apidocs_routing_spec.rb, spec/routing/swagger_ui_routing_spec.rb
- Fixed Swagger problem
- Response example will be follow the common practices. Sources can be found at pivotal tracker 
task #154788840
- #154653947
- #154654269
- #154788840
- #154788839
- #154788838
- #154788837
- #154788836
- #154788781
- nil
=> Fix swagger UI

app/admin/doorkeeper_access_tokens.rb, app/controllers/reviews_controller.rb
- Remove doorkeeper text
155555052
=> Fix doorkeeper

app/admin/doorkeeper_access_tokens.rb, app/controllers/reviews_controller.rb
- Add revoke at in the front end to make it easier to differentiate deleted and not deleted tokens
=> Fix doorkeeper on active admin

app/controllers/concerns/render_errors.rb, app/controllers/tokens_controller.rb, app/models/concerns/swagger_docs/company.rb, config/initializers/custom_token_error_response.rb, spec/spec_helper.rb, spec/support/api_login_helper.rb
=> remove status code from the body

app/serializers/company_serializer.rb, spec/serializers/company_serializer_spec.rb
- Added the strengths and review count to the response for company endpoint
- Company endpoint
- nil
=> Modified company endpoint

app/controllers/concerns/swagger_docs/products.rb, app/models/concerns/swagger_docs/product.rb, app/serializers/product_serializer.rb, spec/serializers/product_serializer_spec.rb
- Added company to the responses
Product CRUD
=> added company to product

app/models/concerns/swagger_docs/service.rb, app/serializers/service_serializer.rb, spec/serializers/service_serializer_spec.rb
=> added company to service

app/controllers/products_controller.rb, app/controllers/reviews_controller.rb, app/controllers/services_controller.rb, app/serializers/product_serializer.rb, app/serializers/review_serializer.rb, app/serializers/service_serializer.rb
- Updated the responses of review endpoint with reviewable object and company object
- #154619368
- nil
=> Add reviewable (product/service) object and company object to response

app/views/swagger_ui/index.html.erb
* Update learn more button to scroll down to anchor
* Update "Leave feedback to help others" title
- #155851728
=> * Update learn more button to scroll down to anchor

app/controllers/reviews_controller.rb, app/models/concerns/swagger_docs/product.rb
- display object (product/service) in show, post, and put review endpoint 
- #154619368
- #154619428
- #154619536
- Nil
=> Update review response

app/models/concerns/swagger_docs/like.rb
- Changed the example value of like endpoint to match response
- Nil
=> Update like endpoint Swagger

app/controllers/application_controller.rb, app/controllers/companies_controller.rb, app/controllers/likes_controller.rb, app/models/company.rb, spec/controllers/companies_controller_spec.rb, spec/models/company_spec.rb, spec/requests/companies_spec.rb
- Added validation on model level for company endpoint
- Nil
=> Add validation on model level

.rubocop.yml, app/models/concerns/swagger_docs/grant.rb, app/models/concerns/swagger_docs/industry.rb, app/serializers/industry_serializer.rb, db/seeds.rb, spec/serializers/industry_serializer_spec.rb
- industry was missing description
=> added missing field

.rubocop.yml, app/controllers/industries_controller.rb, app/models/concerns/swagger_docs/grant.rb, app/models/concerns/swagger_docs/industry.rb, app/serializers/industry_serializer.rb, db/seeds.rb, spec/serializers/industry_serializer_spec.rb
- FIx description not permitted in params
=> FIx description not permitted in params

app/controllers/reviews_controller.rb
Investigate difference behaviour missing params for Review endpoint 
155942184
=> standardize error code

app/controllers/companies_controller.rb, app/models/concerns/swagger_docs/company.rb, app/serializers/company_serializer.rb, spec/controllers/companies_controller_spec.rb, spec/requests/companies_spec.rb, spec/serializers/company_serializer_spec.rb
- Add industry into company endpoint
- #155768104
- Nil
=> Add industry into company

app/controllers/apidocs_controller.rb, app/views/layouts/_header.erb, app/views/swagger_ui/apidoc.html.erb, app/views/swagger_ui/index.html.erb, spec/controllers/reviews_controller_spec.rb, spec/requests/reviews_spec.rb
- Changed from product to company
- #155900921
- Nil
=> changed product review platform to company review platform

app/models/company.rb, app/models/grant.rb, app/models/review.rb, app/models/user.rb, db/migrate/20171207022927_create_companies.rb, db/migrate/20171208030031_create_agencies.rb, db/migrate/20171208032524_create_reviews.rb, db/migrate/20180227023336_create_industries.rb, db/migrate/20180227065808_create_grants.rb, db/migrate/20180307063047_add_description_to_industry.rb, db/migrate/20180307075158_add_fields_to_grant.rb, db/seeds.rb, spec/models/company_spec.rb, spec/models/grant_spec.rb, spec/models/like_spec.rb, spec/models/review_spec.rb, spec/models/user_spec.rb
- Added model validations except for company and agency
=> added model validations except company and agency

app/controllers/reviews_controller.rb
=> Investigate difference behaviour missing params for Review endpoint 

app/controllers/grants_controller.rb, spec/controllers/grants_controller_spec.rb, spec/requests/grants_spec.rb
- Agency should return 404 if not found instead of 400
156004151
=> Fix grant endpoint

app/models/agency.rb
- A more readable error message for agency kind
=> added more helpful kind message

.rubocop.yml, Gemfile
=> Modify to fix heroku deployment

app/controllers/strengths_controller.rb
- Missing swagger from controller
=> added strength to swagger

app/controllers/companies_controller.rb, app/models/company.rb, app/models/concerns/statistics/companies.rb, app/models/concerns/swagger_docs/product.rb, app/models/concerns/swagger_docs/service.rb, app/models/product.rb, app/models/review.rb, app/models/service.rb, app/serializers/associate_company_serializer.rb, app/serializers/product_serializer.rb, app/serializers/service_serializer.rb, db/migrate/20171207022927_create_companies.rb, db/migrate/20171207062601_create_products.rb, db/migrate/20171208024913_create_services.rb, db/schema.rb, spec/concerns/statistics/companies_spec.rb, spec/models/company_spec.rb, spec/models/product_spec.rb, spec/models/service_spec.rb, spec/serializers/product_serializer_spec.rb, spec/serializers/service_serializer_spec.rb
- make reviews_count a column of product/service and company
=> make reviews_count a column of product/service and company

app/controllers/grants_controller.rb
- Grant update should return 400 instead of 500 when {} is provided as params
=> fix grant update error response

Gemfile, Gemfile.lock, app/models/company.rb, spec/models/company_spec.rb
- Add validation for company url
=> add validation for url

app/models/concerns/swagger_docs/review.rb
=> make strength an array

.rubocop.yml, app/controllers/companies_controller.rb, app/controllers/concerns/swagger_docs/companies.rb, app/models/company.rb, config/routes.rb, spec/controllers/companies_controller_spec.rb, spec/requests/companies_spec.rb, spec/routing/companies_routing_spec.rb
- Developer can get clients from Clients endpoint
=> Add clients endpoint

app/controllers/reviews_controller.rb
- review controller params wasnt permitting strength id
=> added strength id to review params

app/models/concerns/swagger_docs/service.rb
=> fix swagger example value for review

app/controllers/companies_controller.rb
=> Fix update comany without industries bug

app/controllers/reviews_controller.rb
- Observed
{
"Parameter missing": [
"param is missing or the value is empty: reviewer_id"
]
}
Expected
{
"Parameter missing": [
"param is missing or the value is empty: review"
]
}
=> added error for missing review

app/controllers/reviews_controller.rb
- Fix minor bug on Review create endpoint
= nil
=> Fix review create bug

app/controllers/reviews_controller.rb, app/models/product.rb, app/models/reviewable.rb, app/models/service.rb, app/serializers/review_serializer.rb, spec/controllers/reviews_controller_spec.rb
- Refactor code in review controller
=> Add reviewable

app/serializers/review_serializer.rb
=> generalise serializers

.rubocop_disabled.yml, app/controllers/agencies_controller.rb, app/controllers/likes_controller.rb, app/models/agency.rb, app/models/commentable.rb, app/models/concerns/swagger_docs/agency.rb, app/models/concerns/swagger_docs/comment.rb, app/models/concerns/swagger_docs/like.rb, app/models/concerns/swagger_docs/review.rb, app/models/like.rb, app/models/likeable.rb, app/models/liker.rb, app/models/review.rb, app/serializers/agency_serializer.rb, app/serializers/like_serializer.rb, db/migrate/20180327055439_change_like_ownership_to_liker.rb, db/schema.rb, db/seeds.rb, spec/controllers/comments_controller_spec.rb, spec/controllers/likes_controller_spec.rb, spec/factories/likes.rb, spec/factories/product_review_likes.rb, spec/factories/service_review_likes.rb, spec/models/like_spec.rb, spec/requests/likes_spec.rb, spec/serializers/like_serializer_spec.rb
- Added object and from to Like endpoitn
- #155764744
- #155900175
-nil
=> Like endpoint from object

app/controllers/reviews_controller.rb
=> make strength plural

app/controllers/comments_controller.rb, app/controllers/likes_controller.rb, app/models/agency.rb, app/models/commenter.rb, app/models/company.rb, app/serializers/comment_serializer.rb, app/serializers/like_serializer.rb, spec/controllers/comments_controller_spec.rb, spec/controllers/likes_controller_spec.rb, spec/requests/comments_spec.rb
- Make Company as a Liker and Commenter
- #156331519
-#156331520
- Nil
=> added Company as Liker and Commenter

app/controllers/agencies_controller.rb, app/controllers/application_controller.rb, app/controllers/aspects_controller.rb, app/controllers/comments_controller.rb, app/controllers/companies_controller.rb, app/controllers/grants_controller.rb, app/controllers/industries_controller.rb, app/controllers/likes_controller.rb, app/controllers/products_controller.rb, app/controllers/reviews_controller.rb, app/controllers/services_controller.rb
- Added missing total and per-page information to header
- #156093042
- Same
=> Fix pagination

app/controllers/agencies_controller.rb, app/controllers/companies_controller.rb, app/controllers/grants_controller.rb
- Image wasn't saving during update for agency and company
=> fixed image update not working

Gemfile, Gemfile.lock, README.md
=> updated readme

app/controllers/companies_controller.rb, app/controllers/concerns/swagger_docs/companies.rb, app/models/company.rb, app/models/concerns/swagger_docs/company.rb, app/serializers/vendor_listing_serializer.rb, config/routes.rb, db/seeds.rb, spec/controllers/companies_controller_spec.rb, spec/models/company_spec.rb, spec/requests/companies_spec.rb, spec/routing/companies_routing_spec.rb, spec/serializers/vendor_listings_serializer_spec.rb
=> Add vendor listing

app/controllers/companies_controller.rb, app/controllers/concerns/swagger_docs/companies.rb, app/controllers/concerns/swagger_docs/projects.rb, app/controllers/concerns/swagger_docs/reviews.rb, app/controllers/grants_controller.rb, app/controllers/projects_controller.rb, app/models/company.rb, app/models/concerns/swagger_docs/company.rb, app/models/project.rb, app/models/review.rb, app/serializers/vendor_listing_serializer.rb, db/seeds.rb, deployment-test.sh, spec/controllers/companies_controller_spec.rb, spec/models/company_spec.rb, spec/requests/companies_spec.rb, spec/serializers/vendor_listings_serializer_spec.rb
=> added review score to vendor listing

app/controllers/companies_controller.rb, app/models/company.rb, spec/models/company_spec.rb
Adjusted API call to include option to sort by newly added.
Adjusted spec to include testing for sort by newly added.
=> Add feature to sort by newly added

app/controllers/companies_controller.rb, app/controllers/grants_controller.rb, app/controllers/projects_controller.rb
=> Add kept to search

Gemfile, Gemfile.lock, app/controllers/application_controller.rb, app/controllers/companies_controller.rb, app/controllers/concerns/swagger_docs/companies.rb, config/locales/en.yml, spec/controllers/companies_controller_spec.rb
Added ransack https://github.com/activerecord-hackery/ransack
=> added fuzzy search

app/controllers/companies_controller.rb, config/locales/en.yml, db/seeds.rb, spec/controllers/companies_controller_spec.rb
=> Add filter search

app/controllers/companies_controller.rb
=> fixed image problem when creating company from search

app/controllers/companies_controller.rb, app/models/company.rb, app/serializers/vendor_listing_serializer.rb, spec/models/company_spec.rb, spec/serializers/vendor_listings_serializer_spec.rb
=> added filter to client and grant

app/controllers/companies_controller.rb, app/controllers/projects_controller.rb, spec/controllers/companies_controller_spec.rb, spec/controllers/projects_controller_spec.rb
- Short description of overall goals of the pull request's commits
- Links to libraries you added
=> Fixed image prob

app/controllers/companies_controller.rb, app/controllers/grants_controller.rb, app/controllers/industries_controller.rb, app/models/company.rb, db/seeds.rb
- Filter now works with newly added
- Added seed data for projects
- Sort grants and industry by name
=> fixed bugs

app/controllers/application_controller.rb, app/controllers/companies_controller.rb, app/controllers/grants_controller.rb, app/models/company.rb, spec/controllers/companies_controller_spec.rb, spec/controllers/grants_controller_spec.rb, spec/models/company_spec.rb, spec/requests/grants_spec.rb
=> Add sort to clients

app/controllers/projects_controller.rb, db/migrate/20180619070321_update_name_of_project.rb, db/schema.rb
=> Fix race condition on project  search endpoints

app/controllers/products_controller.rb, app/controllers/services_controller.rb, config/routes.rb, db/migrate/20180619094704_update_name_of_product_service.rb, db/schema.rb, spec/controllers/products_controller_spec.rb, spec/controllers/services_controller_spec.rb
=> add search for product and service endpoint

app/controllers/concerns/swagger_docs/companies.rb, app/controllers/concerns/swagger_docs/reviews.rb, app/controllers/reviews_controller.rb, app/models/company.rb, app/models/review.rb, app/serializers/review_with_date_serializer.rb, config/routes.rb, db/seeds.rb, spec/controllers/reviews_controller_spec.rb, spec/models/company_spec.rb, spec/serializers/review_with_date_serializer_spec.rb
=> added company review

.rubocop.yml, Gemfile.lock, app/admin/apps.rb
=> Add scope to admin console

app/controllers/companies_controller.rb, app/controllers/projects_controller.rb, app/models/company.rb
- prevent vulnerabilities for sql query for company model
=> added sql_sanitizer to prevent vulnerabilities
